config/routes.rb
Rails.application.routes.draw do
  root to: "home#index" 
   
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :line_items
  resources :carts
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  get 'gallery/search'

 


  get 'admin/login'
  post 'admin/login'
  get  'admin/logout'
  
  resources :stores
  
  get 'home/index'
  get 'home/services'
  get 'home/about'
  get 'home/contact'
  get 'home/pricing'
  get 'home/portfolio'

  





 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :recipe_image
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:recipe_name, :recipe_description, :recipe_calories, :recipe_price , :recipe_image)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_name %>
    <%= form.text_field :recipe_name  %>
  </div>

  <div class="field">
    <%= form.label :recipe_description %>
    <%= form.text_area :recipe_description %>
  </div>

  <div class="field">
    <%= form.label :recipe_calories %>
    <%= form.text_field :recipe_calories %>
  </div>

  <div class="field">
    <%= form.label :recipe_price %>
    <%= form.text_field :recipe_price %>
  </div>

  <div class="field">
    <%= form.label :recipe_image %>
    <%= form.file_field :recipe_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="container">
<h1>Editing Recipe</h1>


<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>
</div>

app/views/stores/index.html.erb
<div style="background-image:url(https://i.pinimg.com/originals/29/ba/f6/29baf6a1fe8325f5789cb83213048d4b.jpg);background-repeat: no-repeat, repeat;background-size: cover;">
<p id="notice"><%= notice %></p>
 
 
<p class="display-4">Recipe Store</p>



<table>
  <thead>
    <tr>
      <th>Recipe name</th>
      <th>Recipe description</th>
      <th>Recipe calories</th>
      <th>Recipe price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <th style="font-size:16px"><%= store.recipe_name %></th>
        <td style="font-size:16px"><%= store.recipe_description %></td>
        <td style="font-size:16px"><%= store.recipe_calories %></td>
        <td style="font-size:16px"><%= store.recipe_price %></td>
        <td style="font-size:16px"><%= link_to 'Show', store %></td>
        <% if  session[:admin] == "admin" %>
         <td style="font-size:16px"><%= link_to 'Edit', edit_store_path(store) %></td>
        <td style="font-size:16px"><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

 

<br>
<% if  session[:admin] == "admin" %>
 <%= link_to 'New Store', new_store_path %>
<% end %>
 
</div>

app/views/stores/new.html.erb
<div class="container">
<p class="display-4">New Recipe</p>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>
</div>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

 
<div class="card" style="width:3rem;border:none;margin-left:300px">
     <%= image_tag(@store.recipe_image) if @store.recipe_image.attached? %>
</div>
 

<p>
  <strong>Recipe name:</strong>
  <%= @store.recipe_name %>
</p>

<p>
  <strong>Recipe description:</strong>
  <%= @store.recipe_description %>
</p>

<p>
  <strong>Recipe calories:</strong>
  <%= @store.recipe_calories %>
</p>

<p>
  <strong>Recipe price:</strong>
  <%= @store.recipe_price %>
</p>

<% if  session[:admin] == "admin" %>
 <%= link_to 'Edit', edit_store_path(@store) %> |
<% end %>
<%= link_to 'Back', stores_path %>